deployment:
  tasks:
    - export DEPLOYPATH=/home/studezvd/jali.studenterb.co.za/
    - echo "Deployment working!" > $DEPLOYPATH/test.txt
    # - /bin/cp -R dist/* $DEPLOYPATH
    # Copy build output to public_html
    - echo "=== Copying files to public_html ===" >> $DEPLOYPATH/deploy.log 2>&1
    - /bin/cp -R portfolio/broswer/* $DEPLOYPATH >> $DEPLOYPATH/deploy.log 2>&1

    # - echo "=== Deployment finished at $(date) ===" >> $DEPLOYPATH/deploy.log 2>&1
